//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fact
    {
        public int Fact_ID { get; set; }
        public Nullable<int> Bank_ID { get; set; }
        public Nullable<int> Branch_ID { get; set; }
        public Nullable<int> Org_ID { get; set; }
        public Nullable<int> Account_ID { get; set; }
        public Nullable<int> Paid_ID { get; set; }
        public Nullable<int> Control_ID { get; set; }
        public Nullable<int> Cheque_ID { get; set; }
        public Nullable<int> Voucher_ID { get; set; }
        public Nullable<int> Bill_ID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> T_Date { get; set; }
        public Nullable<int> Category_ID { get; set; }
        public Nullable<int> V_ID { get; set; }
        public Nullable<decimal> Tax_Amount { get; set; }
        public Nullable<decimal> Tax_Per { get; set; }
        public string imgPath { get; set; }
    }
}
