//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataEntryV1
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Bill_No { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Particulars { get; set; }
        public string Project { get; set; }
        public string Ref { get; set; }
        public Nullable<int> No { get; set; }
        public string Unverified { get; set; }
        public Nullable<long> Bill { get; set; }
        public Nullable<long> Payment { get; set; }
        public Nullable<long> Balance { get; set; }
    }
}
